// Datos de operativos veterinarios — generado automaticamente
// Total: 248 registros
const operativosData = [
  { dia: '21', mes: 'Febrero', anio: 2024, lugar: 'Plaza de Amado Nervo & Kepler' },
  { dia: '22', mes: 'Febrero', anio: 2024, lugar: 'Plaza de Leonardo Da Vinci / Rayen Quitral' },
  { dia: '27', mes: 'Febrero', anio: 2024, lugar: 'Plaza de El Abeto / Isla Condor' },
  { dia: '28', mes: 'Febrero', anio: 2024, lugar: 'Plaza de Isla Grande de Tierra del Fuego / Argos' },
  { dia: '29', mes: 'Febrero', anio: 2024, lugar: 'Plaza de San Francisco de Asís / Aves del Paraíso' },
  { dia: '1', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Las Garzas / Ing. Roberto Llona' },
  { dia: '2', mes: 'Marzo', anio: 2024, lugar: 'Plaza de José Zorrilla / San Juan de la Cruz' },
  { dia: '6', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Butachauques / Meulín' },
  { dia: '7', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Papa San Pedro / Papa San Lino' },
  { dia: '8', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Las Alondras / Los Flamencos' },
  { dia: '9', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Los Pintores / Gil de Castro' },
  { dia: '13', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Los Pintores / Gil de Castro' },
  { dia: '13', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Los Pintores / Gil de Castro' },
  { dia: '14', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Wagner & El Viento Norte (plaza "La Arboleda")' },
  { dia: '14', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Wagner & El Viento Norte (plaza "La Arboleda")' },
  { dia: '15', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Estrella de Belen / Las Brisas' },
  { dia: '16', mes: 'Marzo', anio: 2024, lugar: 'Ricardo Vial 8099 / Junta de Vecinos N°5' },
  { dia: '19', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Dickens & Pirandello' },
  { dia: '20', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Andalucía / Los Capuchinos' },
  { dia: '21', mes: 'Marzo', anio: 2024, lugar: 'Plaza de El Huerto / Federico Mistral Pte' },
  { dia: '22', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Ismael & Jacob' },
  { dia: '23', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Las Murtas / Naranjal' },
  { dia: '26', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Batachauques / Escampavia' },
  { dia: '27', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Las Palomas de San Jose & Lugo' },
  { dia: '28', mes: 'Marzo', anio: 2024, lugar: 'Plaza de Laguna del Maule / Lago Llanquihue' },
  { dia: '3', mes: 'Abril', anio: 2024, lugar: 'Plaza de Puerto Toro / Puerto Consuelo' },
  { dia: '4', mes: 'Abril', anio: 2024, lugar: 'Plaza de San Sebastian / Valladolid' },
  { dia: '5', mes: 'Abril', anio: 2024, lugar: 'Plaza de Narcisa Zurita / Dr. Lehuedé (Plaza Alaska)' },
  { dia: '6', mes: 'Abril', anio: 2024, lugar: 'Plaza de Queule / Tinguiririca' },
  { dia: '7', mes: 'Abril', anio: 2024, lugar: 'Plaza de Escritor Pedro Prado / Valparaíso' },
  { dia: '13', mes: 'Abril', anio: 2024, lugar: 'Plaza de Aves del Paraiso / Min Antonio Varas' },
  { dia: '16', mes: 'Abril', anio: 2024, lugar: 'Plaza de El Tricague / El Anguilucho' },
  { dia: '16', mes: 'Abril', anio: 2024, lugar: 'Plaza de Las Taguas / El Chirigue' },
  { dia: '16', mes: 'Abril', anio: 2024, lugar: 'Plaza de El Tricague / El Anguilucho' },
  { dia: '17', mes: 'Abril', anio: 2024, lugar: 'Plaza de Túnez & Guinea' },
  { dia: '19', mes: 'Abril', anio: 2024, lugar: 'Plaza de San Francisco / Océano' },
  { dia: '21', mes: 'Abril', anio: 2024, lugar: 'Plaza de San Ignacio / Océano' },
  { dia: '22', mes: 'Abril', anio: 2024, lugar: 'Plaza de Pitágoras / Orfeo' },
  { dia: '23', mes: 'Abril', anio: 2024, lugar: 'Plaza de El Olmo / El Pehuén' },
  { dia: '26', mes: 'Abril', anio: 2024, lugar: 'Plaza de El Olmo / El Pehuén' },
  { dia: '27', mes: 'Abril', anio: 2024, lugar: 'Plaza de Aves del Paraíso / Min Antonio Varas' },
  { dia: '27', mes: 'Abril', anio: 2024, lugar: 'Plaza de Pablo Burchard / Arquitecto Jose Vial' },
  { dia: '1', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Pitágoras / Orfeo' },
  { dia: '1', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Las Flores & Jacinto' },
  { dia: '4', mes: 'Mayo', anio: 2024, lugar: 'Plaza de (CANCHA TEXAS) RICARDO VIAL & LAS ENCÍCLICAS' },
  { dia: '9', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Sancho & El Quijote' },
  { dia: '9', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Sancho & El Quijote' },
  { dia: '10', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Federico Garcia Lorca / Vicente Huidobro' },
  { dia: '11', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Liquiñe (Chaura & Lanco)' },
  { dia: '11', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Federico Garcia Lorca / Vicente Huidobro' },
  { dia: '11', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Liquiñe (Chaura & Lanco)' },
  { dia: '13', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Tinguiririca / Queule' },
  { dia: '14', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Tinguiririca / Queule' },
  { dia: '17', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Simon Bolivar (Carahue & Catán)' },
  { dia: '18', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Parque El Molino / El Molino & Opus Seis' },
  { dia: '18', mes: 'Mayo', anio: 2024, lugar: 'Plaza de El Molino / Ing. Reinaldo Muñoz Montt' },
  { dia: '29', mes: 'Mayo', anio: 2024, lugar: 'Plaza de Islas del Sol (Isla Guadalupe / Isla del Sol)' },
  { dia: '1', mes: 'Junio', anio: 2024, lugar: 'Plaza de Talcamavida / Yecomavida' },
  { dia: '1', mes: 'Junio', anio: 2024, lugar: 'Plaza de Caramávida / Talcamavida' },
  { dia: '2', mes: 'Junio', anio: 2024, lugar: 'Plaza de Los Tenores / De la Música' },
  { dia: '2', mes: 'Junio', anio: 2024, lugar: 'Plaza de Víctor Tevah / El Arpa' },
  { dia: '4', mes: 'Junio', anio: 2024, lugar: 'Plaza de Almirante Grau / Luis Uribe' },
  { dia: '5', mes: 'Junio', anio: 2024, lugar: 'Plaza de Batalla de Chacabuco / Cay Cay' },
  { dia: '5', mes: 'Junio', anio: 2024, lugar: 'Plaza de Batalla de Yungay / Llancolén' },
  { dia: '8', mes: 'Junio', anio: 2024, lugar: 'Plaza La Camanchaca (La Marisma / El Estuario)' },
  { dia: '8', mes: 'Junio', anio: 2024, lugar: 'Plaza de Los Vencedores / Brasil' },
  { dia: '8', mes: 'Junio', anio: 2024, lugar: 'Plaza La Camanchaca (La Marisma / El Estuario)' },
  { dia: '15', mes: 'Junio', anio: 2024, lugar: 'Plaza: Los Confines / Campanario' },
  { dia: '15', mes: 'Junio', anio: 2024, lugar: 'Plaza de Los Musicos del Sur (Los Condes & Coliseo)' },
  { dia: '16', mes: 'Junio', anio: 2024, lugar: 'Plaza: Cerdeña / San Marino' },
  { dia: '23', mes: 'Junio', anio: 2024, lugar: 'Sede 10 de abril. Bolivar #6353' },
  { dia: '27', mes: 'Junio', anio: 2024, lugar: 'El Labrador / La Siembra' },
  { dia: '30', mes: 'Junio', anio: 2024, lugar: 'Plaza de Rio Nilo & Alejandria' },
  { dia: '1', mes: 'Julio', anio: 2024, lugar: 'Plaza de Cerdeña / San Marino' },
  { dia: '2', mes: 'Julio', anio: 2024, lugar: 'Plaza de Cerdeña / San Marino' },
  { dia: '3', mes: 'Julio', anio: 2024, lugar: 'Plaza de Zurich / Bruselas' },
  { dia: '4', mes: 'Julio', anio: 2024, lugar: 'Plaza de Río Napon / Río Vaupéz' },
  { dia: '6', mes: 'Julio', anio: 2024, lugar: 'Plaza de Río Napon / Río Vaupéz' },
  { dia: '10', mes: 'Julio', anio: 2024, lugar: 'Plaza de Altarcillo / Pdte. Montt & Atlántida' },
  { dia: '10', mes: 'Julio', anio: 2024, lugar: 'Plaza de Kant & Cuvier' },
  { dia: '11', mes: 'Julio', anio: 2024, lugar: 'Plaza de Kant & Cuvier' },
  { dia: '12', mes: 'Julio', anio: 2024, lugar: 'Plaza de Marta Brunet (Marta Brunet & Reina Ana)' },
  { dia: '12', mes: 'Julio', anio: 2024, lugar: 'Plaza Manuel Rodriguez (Dr. Carlos Ottolenghi & Dr. Carlos Allende)' },
  { dia: '13', mes: 'Julio', anio: 2024, lugar: 'Plaza de Rebeca de Matte / Parque Sur' },
  { dia: '17', mes: 'Julio', anio: 2024, lugar: 'Plaza de Rodio & Polonio' },
  { dia: '19', mes: 'Julio', anio: 2024, lugar: 'Plaza de La Costa / Campaña de Tacna' },
  { dia: '21', mes: 'Julio', anio: 2024, lugar: 'Plaza ubicada entre Pje. La Loma / Pje. La Vihuela' },
  { dia: '25', mes: 'Julio', anio: 2024, lugar: 'Plaza de PAINE / DIAGONAL SUR' },
  { dia: '27', mes: 'Julio', anio: 2024, lugar: 'Plaza de SEIS OTE & UNO NTE' },
  { dia: '28', mes: 'Julio', anio: 2024, lugar: 'Plaza El Estribo (El Estribo con Farellones)' },
  { dia: '4', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Campo de Marte / Parque Norte' },
  { dia: '7', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Los Alamos con Pedro Prado' },
  { dia: '9', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Las Palmas / Pedro de Cordova' },
  { dia: '13', mes: 'Agosto', anio: 2024, lugar: 'Plaza de esquina Los Estudiantes con Los Estudiantes-B' },
  { dia: '13', mes: 'Agosto', anio: 2024, lugar: 'Plaza de esquina Los Estudiantes con Los Estudiantes-B' },
  { dia: '14', mes: 'Agosto', anio: 2024, lugar: 'Plaza La Longo (Huelén Huala & Longotoma)' },
  { dia: '14', mes: 'Agosto', anio: 2024, lugar: 'Plaza La Longo (Huelén Huala & Longotoma)' },
  { dia: '15', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Del Sembrador / Del Parronal' },
  { dia: '16', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Benito Casanova / Alcaldesa Elisa Alvarez' },
  { dia: '18', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Los Lirios / Los Pinos' },
  { dia: '20', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Union Ferroviaria / Arturo Alessandri' },
  { dia: '24', mes: 'Agosto', anio: 2024, lugar: 'Plaza de la Arboleda Sur & Caburgua (Parque Central Quilicura)' },
  { dia: '25', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Mar de la Luna / Salar del Carmen' },
  { dia: '25', mes: 'Agosto', anio: 2024, lugar: 'Plaza de la Arboleda Sur & Caburgua (Parque Central Quilicura)' },
  { dia: '30', mes: 'Agosto', anio: 2024, lugar: 'Plaza de Moluche / Alihuen' },
  { dia: '31', mes: 'Agosto', anio: 2024, lugar: 'La Plaza & Dr Ottolenghi / Junta de Vecinos N°23' },
  { dia: '31', mes: 'Agosto', anio: 2024, lugar: 'La Plaza & Dr Ottolenghi / Junta de Vecinos N°23' },
  { dia: '2', mes: 'Septiembre', anio: 2024, lugar: 'Plaza de La Punta / Felipe Dawes M' },
  { dia: '3', mes: 'Septiembre', anio: 2024, lugar: 'Plaza de San Vicente de Paul / Pasaje Once' },
  { dia: '4', mes: 'Septiembre', anio: 2024, lugar: 'Plaza de Veracruz / San Felipe' },
  { dia: '6', mes: 'Septiembre', anio: 2024, lugar: 'Plaza de Arena (Ponce de León / Ponce de León Cuatro)' },
  { dia: '10', mes: 'Septiembre', anio: 2024, lugar: 'Plaza: C. LA RBLA. & PASAJE REUS NORTE' },
  { dia: '9', mes: 'Octubre', anio: 2024, lugar: 'Plaza de Av. Aeropuerto & Ing. Raul Saez Saez' },
  { dia: '9', mes: 'Octubre', anio: 2024, lugar: 'Plaza Rio Negro (RIO GRANDE & LAGUNA CAUQUENES)' },
  { dia: '16', mes: 'Octubre', anio: 2024, lugar: 'Plaza de Aeropuerto rodelillo / Aeropuerto torquemada' },
  { dia: '3', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Arturo Aldunate Phillips / Victor Ojeda' },
  { dia: '3', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Salitreras / Pdte. Anibal Pinto' },
  { dia: '3', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de La Galaxia / Williams Rebolledo' },
  { dia: '5', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Salitreras / Pdte. Anibal Pinto' },
  { dia: '6', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de: C. La Rbla & C. P. de Gracia' },
  { dia: '6', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Venezuela / La Tierra' },
  { dia: '8', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Bellatrix / Menguante' },
  { dia: '10', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Inés Riesco / Alberto Perez Rodríguez' },
  { dia: '12', mes: 'Noviembre', anio: 2024, lugar: 'Plaza El Cobre: Gorbea & El Cobre' },
  { dia: '13', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Venezuela / La Tierra' },
  { dia: '15', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Las Garzas / La Travesía' },
  { dia: '16', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de: Uno Sur & Seis Oriente' },
  { dia: '17', mes: 'Noviembre', anio: 2024, lugar: 'Plaza El Cobre: Nirivilo / Longaví' },
  { dia: '20', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Santa Florencia / San Josafat' },
  { dia: '20', mes: 'Noviembre', anio: 2024, lugar: 'Plaza Los Tulipanes (Provincias Unidas & Los Tulipanes)' },
  { dia: '21', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Vecinal & Palena' },
  { dia: '21', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de La Galaxia / Williams Rebolledo' },
  { dia: '21', mes: 'Noviembre', anio: 2024, lugar: 'Plaza Los Tulipanes (Provincias Unidas & Los Tulipanes)' },
  { dia: '23', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Luxor / Etiopia' },
  { dia: '23', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Ponce de Leon / Ponce de Zamora' },
  { dia: '24', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Perpetua Freire / Las Dalias' },
  { dia: '27', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de La Galaxia / Williams Rebolledo' },
  { dia: '27', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de Hualaihué / Roberto Duran Valenzuela' },
  { dia: '28', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de La Galaxia / Williams Rebolledo' },
  { dia: '29', mes: 'Noviembre', anio: 2024, lugar: 'Plaza de la Galaxia / Williams Rebolledo' },
  { dia: '3', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de La Galaxia / Williams Rebolledo' },
  { dia: '4', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Hualaihué / Roberto Duran Valenzuela' },
  { dia: '5', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Hector Fuenzalida / Cabo de Hornos' },
  { dia: '5', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de la Reconquista / El Porvenir de Maipú' },
  { dia: '8', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Disprosio / Rutenao' },
  { dia: '11', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Puerto Cisne con Lago Carrera' },
  { dia: '12', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Hector Fuenzalida / Cabo de Hornos' },
  { dia: '13', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Pdte José Manuel Balmaceda / Psje Puerto Octay' },
  { dia: '14', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Luxor / Etiopia' },
  { dia: '15', mes: 'Diciembre', anio: 2024, lugar: 'JJVV 10 de Abril, Bolivar #6353' },
  { dia: '15', mes: 'Diciembre', anio: 2024, lugar: 'JJVV 10 DE ABRIL, BOLIVAR #6353' },
  { dia: '15', mes: 'Diciembre', anio: 2024, lugar: 'JJVV 10 DE ABRIL, BOLIVAR #6353' },
  { dia: '17', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de: Pasaje Catemu / C. Hijuelas' },
  { dia: '17', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Pasaje Catemu / C. Hijuelas' },
  { dia: '18', mes: 'Diciembre', anio: 2024, lugar: 'Plaza de Concejala Sra. Hilda Porras / Los Levitas' },
  { dia: '4', mes: 'Enero', anio: 2025, lugar: 'Plaza Los Bosquinos (Pje. Agua Sta. de Belen & Pje. Calderilla)' },
  { dia: '5', mes: 'Enero', anio: 2025, lugar: 'Plaza de: Pasaje Efesios / Abadias' },
  { dia: '6', mes: 'Enero', anio: 2025, lugar: 'Plaza de: Pasaje Efesios / Abadias' },
  { dia: '8', mes: 'Enero', anio: 2025, lugar: 'Plaza de Ismael Edwards Matte / Andres Amenábar Vergara' },
  { dia: '9', mes: 'Enero', anio: 2025, lugar: 'Plaza de El Labrador / La Siembra' },
  { dia: '10', mes: 'Enero', anio: 2025, lugar: 'Plaza de Trípoli / Etiopía' },
  { dia: '11', mes: 'Enero', anio: 2025, lugar: 'Plaza de Francisco Pizarro / Caleta de Camarones' },
  { dia: '11', mes: 'Enero', anio: 2025, lugar: 'Plaza de Pelarco & Los Beduinos' },
  { dia: '14', mes: 'Enero', anio: 2025, lugar: 'Plaza de: Pje. Timbalero & C. Lago Jeinimeni' },
  { dia: '17', mes: 'Enero', anio: 2025, lugar: 'Plaza de Los Florines / La Fortuna' },
  { dia: '18', mes: 'Enero', anio: 2025, lugar: 'Plaza de Francisco Pizarro / Caleta de Camarones' },
  { dia: '20', mes: 'Enero', anio: 2025, lugar: 'Plaza de El Alcazar Ote. / Liquidambar Nte.' },
  { dia: '23', mes: 'Enero', anio: 2025, lugar: 'Plaza de Los Diamantes / Silvia Pinto' },
  { dia: '25', mes: 'Enero', anio: 2025, lugar: 'Plaza de Los Andes / Vesubio' },
  { dia: '4', mes: 'Febrero', anio: 2025, lugar: 'Plaza de: Salar del Huasco Nte / Salar del Huasco Sur' },
  { dia: '5', mes: 'Febrero', anio: 2025, lugar: 'Plaza de San Alberto / San Pedro' },
  { dia: '6', mes: 'Febrero', anio: 2025, lugar: 'Plaza de San Francisco de Asís / Aves del Paraíso' },
  { dia: '6', mes: 'Febrero', anio: 2025, lugar: 'Plaza de Francisco Pizarro / Punta de Lobos' },
  { dia: '6', mes: 'Febrero', anio: 2025, lugar: 'Plaza de Copihues del Sur / El Huaso' },
  { dia: '8', mes: 'Febrero', anio: 2025, lugar: 'Plaza de Ramón Barros Luco / Oscar Bonilla' },
  { dia: '15', mes: 'Febrero', anio: 2025, lugar: 'Plaza de Egipto / Calle Quillin' },
  { dia: '17', mes: 'Febrero', anio: 2025, lugar: 'Plaza de Jardín del Edén / Psje Los Tulipanes' },
  { dia: '19', mes: 'Febrero', anio: 2025, lugar: 'Plaza de El Arrayán / Universidad Católica' },
  { dia: '20', mes: 'Febrero', anio: 2025, lugar: 'Plaza de Copihues del Sur / El Huaso' },
  { dia: '27', mes: 'Febrero', anio: 2025, lugar: 'Plaza Eucaliptus (Eucaliptus Nte. & El Alcazar Pte.)' },
  { dia: '27', mes: 'Febrero', anio: 2025, lugar: 'Plaza Eucaliptus (Eucaliptus Nte. & El Alcazar Pte.)' },
  { dia: '1', mes: 'Marzo', anio: 2025, lugar: 'Mar del Sur & Luis Pena Guzman' },
  { dia: '3', mes: 'Marzo', anio: 2025, lugar: 'Plaza de El Abeto / Isla Condor' },
  { dia: '4', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Amado Nevero / Kepler' },
  { dia: '5', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Leonardo Da Vinci / Rayen Quitral' },
  { dia: '11', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Isla Grande de Tierra del Fuego / Argos' },
  { dia: '12', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Las Garzas / Ing. Roberto Llona' },
  { dia: '13', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Jose Zorrilla / San Juan de la Cruz' },
  { dia: '15', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Butachauques / Merlín' },
  { dia: '18', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Papa San Pedro / Papa San Lino' },
  { dia: '18', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Los Flamencos / Las Alondras' },
  { dia: '19', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Los Flamencos / Las Alondras' },
  { dia: '20', mes: 'Marzo', anio: 2025, lugar: 'Plaza de El Abeto / Isla Condor' },
  { dia: '25', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Los Pintores / Gil de Castro' },
  { dia: '26', mes: 'Marzo', anio: 2025, lugar: 'Plaza de Los Pintores / Gil de Castro' },
  { dia: '1', mes: 'Abril', anio: 2025, lugar: 'Plaza de Los Pintores / Gil de Castro' },
  { dia: '2', mes: 'Abril', anio: 2025, lugar: 'Plaza de Papa San Pedro / Papa San Lino' },
  { dia: '3', mes: 'Abril', anio: 2025, lugar: 'Plaza de Laguna del Maule / Lago Lanalhue' },
  { dia: '5', mes: 'Abril', anio: 2025, lugar: 'Plaza de Estrella de Belen / Las Brisas' },
  { dia: '15', mes: 'Abril', anio: 2025, lugar: 'Plaza de Lugo / Las Palomas de San José' },
  { dia: '17', mes: 'Abril', anio: 2025, lugar: 'Plaza de Laguna del Maule / Lago Lanalhue' },
  { dia: '23', mes: 'Abril', anio: 2025, lugar: 'Plaza de Ismael & Jacob' },
  { dia: '14', mes: 'Mayo', anio: 2025, lugar: 'Plaza de Laguna Torca / Las Hualas' },
  { dia: '15', mes: 'Mayo', anio: 2025, lugar: 'Plaza de El Concierto / Caburga' },
  { dia: '15', mes: 'Mayo', anio: 2025, lugar: 'Plaza El Altarcillo: Pdte Montt & Atlantida' },
  { dia: '24', mes: 'Mayo', anio: 2025, lugar: 'Plaza El Altarcillo: Pdte Montt & Atlantida' },
  { dia: '25', mes: 'Mayo', anio: 2025, lugar: 'Plaza El Altarcillo: Pdte Montt & Atlantida' },
  { dia: '28', mes: 'Mayo', anio: 2025, lugar: 'Plaza El Altarcillo: Pdte Montt & Atlantida' },
  { dia: '28', mes: 'Mayo', anio: 2025, lugar: 'Plaza El Altarcillo: Pdte Montt & Atlantida' },
  { dia: '29', mes: 'Mayo', anio: 2025, lugar: 'Plaza de Burgos / Cataluña' },
  { dia: '29', mes: 'Mayo', anio: 2025, lugar: 'Plaza de Burgos / Cataluña' },
  { dia: '1', mes: 'Junio', anio: 2025, lugar: 'Junta de Vecinos 10 de Abril / Bolivar 6353' },
  { dia: '3', mes: 'Junio', anio: 2025, lugar: 'Plaza de Los Alamos / Pedro Prado' },
  { dia: '4', mes: 'Junio', anio: 2025, lugar: 'Plaza de Batalla de Chacabuco / Cay Cay' },
  { dia: '9', mes: 'Junio', anio: 2025, lugar: 'Plaza de Butachauques / Escampavía' },
  { dia: '10', mes: 'Junio', anio: 2025, lugar: 'Plaza de Aves del Paraiso / Min Antonio Varas' },
  { dia: '11', mes: 'Junio', anio: 2025, lugar: 'Plaza de Liceo Maipu / Veinticinco de Diciembre' },
  { dia: '20', mes: 'Junio', anio: 2025, lugar: 'Plaza de San Marino / Cardeña' },
  { dia: '21', mes: 'Junio', anio: 2025, lugar: 'Plaza de Aves del Paraiso / Ing. Pedro Gallo' },
  { dia: '24', mes: 'Junio', anio: 2025, lugar: 'Plaza de Pedro de Cordova / Martin de Soler' },
  { dia: '25', mes: 'Junio', anio: 2025, lugar: 'Plaza de Gabriela Mistral / Félix Margoz' },
  { dia: '26', mes: 'Junio', anio: 2025, lugar: 'Plaza de Los Cometas / Perseo' },
  { dia: '1', mes: 'Julio', anio: 2025, lugar: 'Plaza de San Marino / Cerdaña' },
  { dia: '2', mes: 'Julio', anio: 2025, lugar: 'Plaza de Los Caracoles / Mamiña' },
  { dia: '3', mes: 'Julio', anio: 2025, lugar: 'Plaza de Río Blanco / Río Grande' },
  { dia: '7', mes: 'Julio', anio: 2025, lugar: 'Plaza de Cristobal Colon / Rodrigo de Bastidas' },
  { dia: '8', mes: 'Julio', anio: 2025, lugar: 'Plaza de Luis Maturana Vega / Achao' },
  { dia: '9', mes: 'Julio', anio: 2025, lugar: 'Plaza entre La Vihuela / La Loma' },
  { dia: '12', mes: 'Julio', anio: 2025, lugar: 'Plaza de Parque Norte / Rebeca Matte' },
  { dia: '15', mes: 'Julio', anio: 2025, lugar: 'Plaza de Parque Norte / Rebeca Matte' },
  { dia: '5', mes: 'Agosto', anio: 2025, lugar: 'Plaza de Las Palmas / Pedro de Córdova' },
  { dia: '8', mes: 'Agosto', anio: 2025, lugar: 'Plaza de Campo de Marte / Paque Nte.' },
  { dia: '25', mes: 'Agosto', anio: 2025, lugar: 'Plaza de Alihuen & Huada' },
  { dia: '27', mes: 'Agosto', anio: 2025, lugar: 'Plaza de Las Lluvias / Los Tornados' },
  { dia: '2', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de Huelén Huala / Fresia Oliva' },
  { dia: '6', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de Diego Poblete / Alcaldesa Elisa Alvarez' },
  { dia: '7', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de El Estribo / Farellones' },
  { dia: '09', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de Campanario / Los Confines' },
  { dia: '10', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de Campanario / Los Confines' },
  { dia: '13', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de Dr. Carlos Allende / Dr. Carlos Ottolenghi' },
  { dia: '14', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de: Oceáno Atlántico / Oceáno Pacífico Sur' },
  { dia: '23', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de Victor Tevah / Ramón Vinay' },
  { dia: '24', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de Santa Liliana / Glasgow Uno' },
  { dia: '28', mes: 'Septiembre', anio: 2025, lugar: 'Plaza de Santa Emilia & Nor Pte.' },
  { dia: '2', mes: 'Octubre', anio: 2025, lugar: 'Plaza de Ponce de León / Ponce de Zamora' },
  { dia: '5', mes: 'Octubre', anio: 2025, lugar: 'Bolivar #6353 (Junta de Vecinos)' },
  { dia: '11', mes: 'Octubre', anio: 2025, lugar: 'Plaza de Manquehue / Carriel Sur' },
  { dia: '16', mes: 'Octubre', anio: 2025, lugar: 'Plaza de Papa San Pedro / Papa San Lino' },
];